// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
#include "arduino_secrets.h"

const char DEVICE_LOGIN_NAME[]  = "3aa00351-553f-4c94-be55-322dbfcd2e58";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password


int consumption;
int light;
bool dim_on;
bool presence;
bool strong_on;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(consumption, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(light, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(dim_on, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(presence, READ, 2 * SECONDS, NULL);
  ArduinoCloud.addProperty(strong_on, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
